package org.omg.Security;

/**
* org/omg/Security/CommunicationDirectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/


// secure invocation policy applies
public final class CommunicationDirectionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.Security.CommunicationDirection value = null;

  public CommunicationDirectionHolder ()
  {
  }

  public CommunicationDirectionHolder (org.omg.Security.CommunicationDirection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.Security.CommunicationDirectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.Security.CommunicationDirectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.Security.CommunicationDirectionHelper.type ();
  }

}
