package org.omg.Security;


/**
* org/omg/Security/DCESecureInteroperability.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public interface DCESecureInteroperability
{
  public static final int value = (int)(9L);
}
