package org.omg.Security;


/**
* org/omg/Security/EstablishTrust.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class EstablishTrust implements org.omg.CORBA.portable.IDLEntity
{
  public boolean trust_in_client = false;
  public boolean trust_in_target = false;

  public EstablishTrust ()
  {
  } // ctor

  public EstablishTrust (boolean _trust_in_client, boolean _trust_in_target)
  {
    trust_in_client = _trust_in_client;
    trust_in_target = _trust_in_target;
  } // ctor

} // class EstablishTrust
