package org.omg.Security;


/**
* org/omg/Security/ExtensibleFamily.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class ExtensibleFamily implements org.omg.CORBA.portable.IDLEntity
{
  public short family_definer = (short)0;
  public short family = (short)0;

  public ExtensibleFamily ()
  {
  } // ctor

  public ExtensibleFamily (short _family_definer, short _family)
  {
    family_definer = _family_definer;
    family = _family;
  } // ctor

} // class ExtensibleFamily
