package org.omg.Security;


/**
* org/omg/Security/OpaqueBuffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class OpaqueBuffer implements org.omg.CORBA.portable.IDLEntity
{
  public byte buffer[] = null;
  public int startpos = (int)0;
  public int endpos = (int)0;

  public OpaqueBuffer ()
  {
  } // ctor

  public OpaqueBuffer (byte[] _buffer, int _startpos, int _endpos)
  {
    buffer = _buffer;
    startpos = _startpos;
    endpos = _endpos;
  } // ctor

} // class OpaqueBuffer
