package org.omg.Security;


/**
* org/omg/Security/OptionsDirectionPair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class OptionsDirectionPair implements org.omg.CORBA.portable.IDLEntity
{
  public short options = (short)0;
  public org.omg.Security.CommunicationDirection direction = null;

  public OptionsDirectionPair ()
  {
  } // ctor

  public OptionsDirectionPair (short _options, org.omg.Security.CommunicationDirection _direction)
  {
    options = _options;
    direction = _direction;
  } // ctor

} // class OptionsDirectionPair
