package org.omg.Security;

/**
* org/omg/Security/QOPHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/


// for an object reference and used to protect messages
public final class QOPHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.Security.QOP value = null;

  public QOPHolder ()
  {
  }

  public QOPHolder (org.omg.Security.QOP initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.Security.QOPHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.Security.QOPHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.Security.QOPHelper.type ();
  }

}
