package org.omg.Security;


/**
* org/omg/Security/RightsListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class RightsListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.Security.Right value[] = null;

  public RightsListHolder ()
  {
  }

  public RightsListHolder (org.omg.Security.Right[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.Security.RightsListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.Security.RightsListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.Security.RightsListHelper.type ();
  }

}
