package org.omg.Security;


/**
* org/omg/Security/SecAttribute.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class SecAttribute implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.Security.AttributeType attribute_type = null;
  public byte defining_authority[] = null;
  public byte value[] = null;

  public SecAttribute ()
  {
  } // ctor

  public SecAttribute (org.omg.Security.AttributeType _attribute_type, byte[] _defining_authority, byte[] _value)
  {
    attribute_type = _attribute_type;
    defining_authority = _defining_authority;
    value = _value;
  } // ctor

} // class SecAttribute
