package org.omg.Security;


/**
* org/omg/Security/SecurityContextType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/Security.idl
* 14 Август 2012 г. 21:55:45 EEST
*/


// Type of SecurityContext
public class SecurityContextType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static org.omg.Security.SecurityContextType[] __array = new org.omg.Security.SecurityContextType [__size];

  public static final int _SecClientSecurityContext = 0;
  public static final org.omg.Security.SecurityContextType SecClientSecurityContext = new org.omg.Security.SecurityContextType(_SecClientSecurityContext);
  public static final int _SecServerSecurityContext = 1;
  public static final org.omg.Security.SecurityContextType SecServerSecurityContext = new org.omg.Security.SecurityContextType(_SecServerSecurityContext);

  public int value ()
  {
    return __value;
  }

  public static org.omg.Security.SecurityContextType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SecurityContextType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SecurityContextType
