package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/ControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface ControlOperations 
{
  org.omg.CosTransactions.Terminator get_terminator () throws org.omg.CosTransactions.Unavailable;
  org.omg.CosTransactions.Coordinator get_coordinator () throws org.omg.CosTransactions.Unavailable;
} // interface ControlOperations
