package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/CurrentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// Current transaction
public interface CurrentOperations  extends org.omg.CORBA.CurrentOperations
{
  void begin () throws org.omg.CosTransactions.SubtransactionsUnavailable;
  void commit (boolean report_heuristics) throws org.omg.CosTransactions.NoTransaction, org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard;
  void rollback () throws org.omg.CosTransactions.NoTransaction;
  void rollback_only () throws org.omg.CosTransactions.NoTransaction;
  org.omg.CosTransactions.Status get_status ();
  String get_transaction_name ();
  void set_timeout (int seconds);
  int get_timeout ();
  org.omg.CosTransactions.Control get_control ();
  org.omg.CosTransactions.Control suspend ();
  void resume (org.omg.CosTransactions.Control which) throws org.omg.CosTransactions.InvalidControl;
} // interface CurrentOperations
