package org.omg.CosTransactions;

/**
* org/omg/CosTransactions/CurrentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// Current transaction
public final class CurrentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CosTransactions.Current value = null;

  public CurrentHolder ()
  {
  }

  public CurrentHolder (org.omg.CosTransactions.Current initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CosTransactions.CurrentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CosTransactions.CurrentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CosTransactions.CurrentHelper.type ();
  }

}
