package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/HeuristicRollback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class HeuristicRollback extends org.omg.CORBA.UserException
{

  public HeuristicRollback ()
  {
    super(HeuristicRollbackHelper.id());
  } // ctor


  public HeuristicRollback (String $reason)
  {
    super(HeuristicRollbackHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicRollback
