package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/HeuristicMixed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class HeuristicMixed extends org.omg.CORBA.UserException
{

  public HeuristicMixed ()
  {
    super(HeuristicMixedHelper.id());
  } // ctor


  public HeuristicMixed (String $reason)
  {
    super(HeuristicMixedHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicMixed
