package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/HeuristicHazard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class HeuristicHazard extends org.omg.CORBA.UserException
{

  public HeuristicHazard ()
  {
    super(HeuristicHazardHelper.id());
  } // ctor


  public HeuristicHazard (String $reason)
  {
    super(HeuristicHazardHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicHazard
