package org.omg.CosTransactions;

/**
* org/omg/CosTransactions/InactiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class InactiveHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CosTransactions.Inactive value = null;

  public InactiveHolder ()
  {
  }

  public InactiveHolder (org.omg.CosTransactions.Inactive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CosTransactions.InactiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CosTransactions.InactiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CosTransactions.InactiveHelper.type ();
  }

}
