package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/InvalidControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class InvalidControl extends org.omg.CORBA.UserException
{

  public InvalidControl ()
  {
    super(InvalidControlHelper.id());
  } // ctor


  public InvalidControl (String $reason)
  {
    super(InvalidControlHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidControl
