package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/NotSubtransaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class NotSubtransaction extends org.omg.CORBA.UserException
{

  public NotSubtransaction ()
  {
    super(NotSubtransactionHelper.id());
  } // ctor


  public NotSubtransaction (String $reason)
  {
    super(NotSubtransactionHelper.id() + "  " + $reason);
  } // ctor

} // class NotSubtransaction
