package org.omg.CosTransactions;

/**
* org/omg/CosTransactions/otid_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class otid_tHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CosTransactions.otid_t value = null;

  public otid_tHolder ()
  {
  }

  public otid_tHolder (org.omg.CosTransactions.otid_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CosTransactions.otid_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CosTransactions.otid_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CosTransactions.otid_tHelper.type ();
  }

}
