package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/PropagationContext.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class PropagationContext implements org.omg.CORBA.portable.IDLEntity
{
  public int timeout = (int)0;
  public org.omg.CosTransactions.TransIdentity current = null;
  public org.omg.CosTransactions.TransIdentity parents[] = null;
  public org.omg.CORBA.Any implementation_specific_data = null;

  public PropagationContext ()
  {
  } // ctor

  public PropagationContext (int _timeout, org.omg.CosTransactions.TransIdentity _current, org.omg.CosTransactions.TransIdentity[] _parents, org.omg.CORBA.Any _implementation_specific_data)
  {
    timeout = _timeout;
    current = _current;
    parents = _parents;
    implementation_specific_data = _implementation_specific_data;
  } // ctor

} // class PropagationContext
