package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/Requires_unshared.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface Requires_unshared
{
  public static final short value = (short)(5);
}
