package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SubtransactionsUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class SubtransactionsUnavailable extends org.omg.CORBA.UserException
{

  public SubtransactionsUnavailable ()
  {
    super(SubtransactionsUnavailableHelper.id());
  } // ctor


  public SubtransactionsUnavailable (String $reason)
  {
    super(SubtransactionsUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SubtransactionsUnavailable
