package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SubtransactionAwareResourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface SubtransactionAwareResourceOperations  extends org.omg.CosTransactions.ResourceOperations
{
  void commit_subtransaction (org.omg.CosTransactions.Coordinator parent);
  void rollback_subtransaction ();
} // interface SubtransactionAwareResourceOperations
