package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SynchronizationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// Inheritance from TransactionalObject is for backward compatability //
public interface SynchronizationOperations  extends org.omg.CosTransactions.TransactionalObjectOperations
{
  void before_completion ();
  void after_completion (org.omg.CosTransactions.Status s);
} // interface SynchronizationOperations
