package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SynchronizationUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class SynchronizationUnavailable extends org.omg.CORBA.UserException
{

  public SynchronizationUnavailable ()
  {
    super(SynchronizationUnavailableHelper.id());
  } // ctor


  public SynchronizationUnavailable (String $reason)
  {
    super(SynchronizationUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SynchronizationUnavailable
