package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/Synchronization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// Inheritance from TransactionalObject is for backward compatability //
public interface Synchronization extends SynchronizationOperations, org.omg.CosTransactions.TransactionalObject, org.omg.CORBA.portable.IDLEntity 
{
} // interface Synchronization
