package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/TerminatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface TerminatorOperations 
{
  void commit (boolean report_heuristics) throws org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard;
  void rollback ();
} // interface TerminatorOperations
