package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/TransIdentity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class TransIdentity implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CosTransactions.Coordinator coord = null;
  public org.omg.CosTransactions.Terminator term = null;
  public org.omg.CosTransactions.otid_t otid = null;

  public TransIdentity ()
  {
  } // ctor

  public TransIdentity (org.omg.CosTransactions.Coordinator _coord, org.omg.CosTransactions.Terminator _term, org.omg.CosTransactions.otid_t _otid)
  {
    coord = _coord;
    term = _term;
    otid = _otid;
  } // ctor

} // class TransIdentity
