package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/Unavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTransactions.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class Unavailable extends org.omg.CORBA.UserException
{

  public Unavailable ()
  {
    super(UnavailableHelper.id());
  } // ctor


  public Unavailable (String $reason)
  {
    super(UnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class Unavailable
