package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/_CurrentStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public class _CurrentStub extends org.omg.CORBA.portable.ObjectImpl implements org.omg.SecurityLevel2.Current
{


  // Thread specific
  public org.omg.SecurityLevel2.ReceivedCredentials received_credentials ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_received_credentials", true);
                $in = _invoke ($out);
                org.omg.SecurityLevel2.ReceivedCredentials $result = org.omg.SecurityLevel2.ReceivedCredentialsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return received_credentials (        );
            } finally {
                _releaseReply ($in);
            }
  } // received_credentials


  // thread specific operations
  public org.omg.Security.SecAttribute[] get_attributes (org.omg.Security.AttributeType[] ttributes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_attributes", true);
                org.omg.Security.AttributeTypeListHelper.write ($out, ttributes);
                $in = _invoke ($out);
                org.omg.Security.SecAttribute $result[] = org.omg.Security.AttributeListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_attributes (ttributes        );
            } finally {
                _releaseReply ($in);
            }
  } // get_attributes

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SecurityLevel2/Current:1.0", 
    "IDL:omg.org/SecurityLevel1/Current:1.0", 
    "IDL:CORBA/Current:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CurrentStub
