package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/AccessDecisionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface AccessDecisionOperations 
{
  boolean access_allowed (org.omg.SecurityLevel2.Credentials[] cred_list, org.omg.CORBA.Object target, String operation_name, String target_interface_name);
} // interface AccessDecisionOperations
