package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/AuditChannelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface AuditChannelOperations 
{
  void audit_write (org.omg.Security.AuditEventType event_type, org.omg.SecurityLevel2.Credentials[] creds, org.omg.TimeBase.UtcT time, org.omg.Security.SelectorValue[] descriptors, org.omg.CORBA.Any event_specific_data);
  int audit_channel_id ();
} // interface AuditChannelOperations
