package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/CurrentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface CurrentOperations  extends org.omg.SecurityLevel1.CurrentOperations
{

  // Thread specific
  org.omg.SecurityLevel2.ReceivedCredentials received_credentials ();
} // interface CurrentOperations
