package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/DelegationDirectivePolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface DelegationDirectivePolicyOperations  extends org.omg.CORBA.PolicyOperations
{
  org.omg.Security.DelegationDirective delegation_directive ();
} // interface DelegationDirectivePolicyOperations
