package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/ReceivedCredentialsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface ReceivedCredentialsOperations  extends org.omg.SecurityLevel2.CredentialsOperations
{
  org.omg.SecurityLevel2.Credentials accepting_credentials ();
  short association_options_used ();
  org.omg.Security.DelegationState delegation_state ();
  org.omg.Security.DelegationMode delegation_mode ();
} // interface ReceivedCredentialsOperations
