package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/RequiredRights.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// RequiredRights Interface
public interface RequiredRights extends RequiredRightsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RequiredRights
