package org.omg.SecurityLevel2;

/**
* org/omg/SecurityLevel2/TargetCredentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public final class TargetCredentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.SecurityLevel2.TargetCredentials value = null;

  public TargetCredentialsHolder ()
  {
  }

  public TargetCredentialsHolder (org.omg.SecurityLevel2.TargetCredentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.SecurityLevel2.TargetCredentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.SecurityLevel2.TargetCredentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.SecurityLevel2.TargetCredentialsHelper.type ();
  }

}
