package org.omg.SecurityLevel2;


/**
* org/omg/SecurityLevel2/TargetCredentialsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel2.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface TargetCredentialsOperations  extends org.omg.SecurityLevel2.CredentialsOperations
{
  org.omg.SecurityLevel2.Credentials initiating_credentials ();
  short association_options_used ();
} // interface TargetCredentialsOperations
