package org.omg.SecurityLevel1;


/**
* org/omg/SecurityLevel1/CurrentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SecurityLevel1.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


/* */
public interface CurrentOperations  extends org.omg.CORBA.CurrentOperations
{

  // thread specific operations
  org.omg.Security.SecAttribute[] get_attributes (org.omg.Security.AttributeType[] ttributes);
} // interface CurrentOperations
