package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/CompoundSecMechList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class CompoundSecMechList implements org.omg.CORBA.portable.IDLEntity
{
  public boolean stateful = false;
  public org.omg.CSIIOP.CompoundSecMech mechanism_list[] = null;

  public CompoundSecMechList ()
  {
  } // ctor

  public CompoundSecMechList (boolean _stateful, org.omg.CSIIOP.CompoundSecMech[] _mechanism_list)
  {
    stateful = _stateful;
    mechanism_list = _mechanism_list;
  } // ctor

} // class CompoundSecMechList
