package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/IdentityAssertion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface IdentityAssertion
{
  public static final short value = (short)(1024);
}
