package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/SAS_ContextSec.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class SAS_ContextSec implements org.omg.CORBA.portable.IDLEntity
{
  public short target_supports = (short)0;
  public short target_requires = (short)0;
  public org.omg.CSIIOP.ServiceConfiguration privilege_authorities[] = null;
  public byte supported_naming_mechanisms[][] = null;
  public int supported_identity_types = (int)0;

  public SAS_ContextSec ()
  {
  } // ctor

  public SAS_ContextSec (short _target_supports, short _target_requires, org.omg.CSIIOP.ServiceConfiguration[] _privilege_authorities, byte[][] _supported_naming_mechanisms, int _supported_identity_types)
  {
    target_supports = _target_supports;
    target_requires = _target_requires;
    privilege_authorities = _privilege_authorities;
    supported_naming_mechanisms = _supported_naming_mechanisms;
    supported_identity_types = _supported_identity_types;
  } // ctor

} // class SAS_ContextSec
