package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/SCS_GeneralNames.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface SCS_GeneralNames
{
  public static final int value = (int)((int)(org.omg.CSI.OMGVMCID.value | 0L));
}
