package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/ServiceConfigurationListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class ServiceConfigurationListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CSIIOP.ServiceConfiguration value[] = null;

  public ServiceConfigurationListHolder ()
  {
  }

  public ServiceConfigurationListHolder (org.omg.CSIIOP.ServiceConfiguration[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CSIIOP.ServiceConfigurationListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CSIIOP.ServiceConfigurationListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CSIIOP.ServiceConfigurationListHelper.type ();
  }

}
