package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/ServiceConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class ServiceConfiguration implements org.omg.CORBA.portable.IDLEntity
{
  public int syntax = (int)0;
  public byte name[] = null;

  public ServiceConfiguration ()
  {
  } // ctor

  public ServiceConfiguration (int _syntax, byte[] _name)
  {
    syntax = _syntax;
    name = _name;
  } // ctor

} // class ServiceConfiguration
