package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/ServiceSpecificNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class ServiceSpecificNameHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ServiceSpecificNameHolder ()
  {
  }

  public ServiceSpecificNameHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CSIIOP.ServiceSpecificNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CSIIOP.ServiceSpecificNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CSIIOP.ServiceSpecificNameHelper.type ();
  }

}
