package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/TAG_SECIOP_SEC_TRANS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface TAG_SECIOP_SEC_TRANS
{

  // Tagged component for configuring SECIOP as a CSIv2 transport mechanism
  public static final int value = (int)(35L);
}
