package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/TLS_SEC_TRANS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class TLS_SEC_TRANS implements org.omg.CORBA.portable.IDLEntity
{
  public short target_supports = (short)0;
  public short target_requires = (short)0;
  public org.omg.CSIIOP.TransportAddress addresses[] = null;

  public TLS_SEC_TRANS ()
  {
  } // ctor

  public TLS_SEC_TRANS (short _target_supports, short _target_requires, org.omg.CSIIOP.TransportAddress[] _addresses)
  {
    target_supports = _target_supports;
    target_requires = _target_requires;
    addresses = _addresses;
  } // ctor

} // class TLS_SEC_TRANS
