package org.omg.CSIIOP;


/**
* org/omg/CSIIOP/TransportAddress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class TransportAddress implements org.omg.CORBA.portable.IDLEntity
{
  public String host_name = null;
  public short port = (short)0;

  public TransportAddress ()
  {
  } // ctor

  public TransportAddress (String _host_name, short _port)
  {
    host_name = _host_name;
    port = _port;
  } // ctor

} // class TransportAddress
