package org.omg.CSIIOP;

/**
* org/omg/CSIIOP/TransportAddressHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSIIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class TransportAddressHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CSIIOP.TransportAddress value = null;

  public TransportAddressHolder ()
  {
  }

  public TransportAddressHolder (org.omg.CSIIOP.TransportAddress initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CSIIOP.TransportAddressHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CSIIOP.TransportAddressHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CSIIOP.TransportAddressHelper.type ();
  }

}
