package org.omg.CSI;


/**
* org/omg/CSI/AuthorizationElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class AuthorizationElement implements org.omg.CORBA.portable.IDLEntity
{
  public int the_type = (int)0;
  public byte the_element[] = null;

  public AuthorizationElement ()
  {
  } // ctor

  public AuthorizationElement (int _the_type, byte[] _the_element)
  {
    the_type = _the_type;
    the_element = _the_element;
  } // ctor

} // class AuthorizationElement
