package org.omg.CSI;


/**
* org/omg/CSI/GSS_NT_Export_Name_OID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface GSS_NT_Export_Name_OID
{

  // gss-api-exported-name(4) }
  public static final String value = "oid:1.3.6.1.5.6.4";
}
