package org.omg.CSI;


/**
* org/omg/CSI/ITTAbsent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface ITTAbsent
{

  // OMG. All IdentityTokenType constants shall be a power of 2.
  public static final int value = (int)(0L);
}
