package org.omg.CSI;


/**
* org/omg/CSI/ITTX509CertChain.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface ITTX509CertChain
{
  public static final int value = (int)(4L);
}
