package org.omg.CSI;


/**
* org/omg/CSI/KRB5MechOID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface KRB5MechOID
{

  // gssapi(2) krb5(2) }
  public static final String value = "oid:1.2.840.113554.1.2.2";
}
