package org.omg.CSI;


/**
* org/omg/CSI/X501DistinguishedNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/


// octets containing the ASN.1 encoding.
public final class X501DistinguishedNameHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public X501DistinguishedNameHolder ()
  {
  }

  public X501DistinguishedNameHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CSI.X501DistinguishedNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CSI.X501DistinguishedNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CSI.X501DistinguishedNameHelper.type ();
  }

}
