package org.omg.CSI;


/**
* org/omg/CSI/X509AttributeCertChain.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CSI.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface X509AttributeCertChain
{

  // in [IETF ID PKIXAC].
  public static final int value = (int)((int)(org.omg.CSI.OMGVMCID.value | 1L));
}
