package org.omg.SSLIOP;


/**
* org/omg/SSLIOP/SSL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SSLIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class SSL implements org.omg.CORBA.portable.IDLEntity
{
  public short target_supports = (short)0;
  public short target_requires = (short)0;
  public short port = (short)0;

  public SSL ()
  {
  } // ctor

  public SSL (short _target_supports, short _target_requires, short _port)
  {
    target_supports = _target_supports;
    target_requires = _target_requires;
    port = _port;
  } // ctor

} // class SSL
