package org.omg.SSLIOP;

/**
* org/omg/SSLIOP/SSLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/SSLIOP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class SSLHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.SSLIOP.SSL value = null;

  public SSLHolder ()
  {
  }

  public SSLHolder (org.omg.SSLIOP.SSL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.SSLIOP.SSLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.SSLIOP.SSLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.SSLIOP.SSLHelper.type ();
  }

}
