package org.omg.CosTSInteroperation;


/**
* org/omg/CosTSInteroperation/TAG_OTS_POLICY.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTSInteroperation.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public interface TAG_OTS_POLICY
{
  public static final int value = (int)(31L);
}
