package org.omg.CosTSInteroperation;

/**
* org/omg/CosTSInteroperation/TransactionPolicyComponentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTSInteroperation.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class TransactionPolicyComponentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CosTSInteroperation.TransactionPolicyComponent value = null;

  public TransactionPolicyComponentHolder ()
  {
  }

  public TransactionPolicyComponentHolder (org.omg.CosTSInteroperation.TransactionPolicyComponent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CosTSInteroperation.TransactionPolicyComponentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CosTSInteroperation.TransactionPolicyComponentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CosTSInteroperation.TransactionPolicyComponentHelper.type ();
  }

}
