package org.omg.CosTSInteroperation;


/**
* org/omg/CosTSInteroperation/TransactionPolicyComponent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/CosTSInteroperation.idl
* 14 Август 2012 г. 21:55:45 EEST
*/

public final class TransactionPolicyComponent implements org.omg.CORBA.portable.IDLEntity
{
  public short tpv = (short)0;

  public TransactionPolicyComponent ()
  {
  } // ctor

  public TransactionPolicyComponent (short _tpv)
  {
    tpv = _tpv;
  } // ctor

} // class TransactionPolicyComponent
