package org.omg.GSSUP;

/**
* org/omg/GSSUP/ErrorTokenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/GSSUP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class ErrorTokenHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.GSSUP.ErrorToken value = null;

  public ErrorTokenHolder ()
  {
  }

  public ErrorTokenHolder (org.omg.GSSUP.ErrorToken initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.GSSUP.ErrorTokenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.GSSUP.ErrorTokenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.GSSUP.ErrorTokenHelper.type ();
  }

}
