package org.omg.GSSUP;


/**
* org/omg/GSSUP/GSS_UP_S_G_BAD_TARGET.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/GSSUP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface GSS_UP_S_G_BAD_TARGET
{

  // not match a target_name in a mechanism definition of the target.
  public static final int value = (int)(4L);
}
