package org.omg.GSSUP;


/**
* org/omg/GSSUP/GSSUPMechOID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/GSSUP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public interface GSSUPMechOID
{

  // security (1) authentication (1) gssup-mechanism (1) }
  public static final String value = "oid:2.23.130.1.1.1";
}
