package org.omg.GSSUP;

/**
* org/omg/GSSUP/InitialContextTokenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/GSSUP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class InitialContextTokenHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.GSSUP.InitialContextToken value = null;

  public InitialContextTokenHolder ()
  {
  }

  public InitialContextTokenHolder (org.omg.GSSUP.InitialContextToken initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.GSSUP.InitialContextTokenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.GSSUP.InitialContextTokenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.GSSUP.InitialContextTokenHelper.type ();
  }

}
