package org.omg.GSSUP;


/**
* org/omg/GSSUP/InitialContextToken.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/yoko-1.0/yoko-spec-corba/src/main/idl/GSSUP.idl
* 14 Август 2012 г. 21:55:46 EEST
*/

public final class InitialContextToken implements org.omg.CORBA.portable.IDLEntity
{
  public byte username[] = null;
  public byte password[] = null;
  public byte target_name[] = null;

  public InitialContextToken ()
  {
  } // ctor

  public InitialContextToken (byte[] _username, byte[] _password, byte[] _target_name)
  {
    username = _username;
    password = _password;
    target_name = _target_name;
  } // ctor

} // class InitialContextToken
